In [1]:
#Príklady na tvorbu a operácie s Poliami v NumPy

In [2]:
import numpy as np

In [3]:
A = np.array([2,3,5])

In [4]:
print(A)

[2 3 5]


In [5]:
#printovať vieme aj bez funkcie print len pomocou vypisania premennej
#platí len pre v jupyter notebook, avšak printuje typ objektu a jeho obsah

A

array([2, 3, 5])

In [6]:
A.dtype

dtype('int64')

In [7]:
B = np.array([2,3,6])

In [13]:
C = A - B
C1 = A + B
C2 = A * B
#pomocou NumPy vieme robiť aj zaujimavé numerické operácie s maticami
for i in range(0,3):
    print(C+i)

[ 0  0 -1]
[1 1 0]
[2 2 1]


In [14]:
C = np.array([2.6, 4.58, 6.25])

In [15]:
C.dtype

dtype('float64')

In [16]:
C

array([2.6 , 4.58, 6.25])

In [17]:
#vytvorenie matice pomocou arange

In [18]:
D = np.arange(15)
D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
#vytvorenie matice pomocou arange
#a zadelenie do piatich samostatnych matic po 3elementy

In [20]:
E = np.arange(15).reshape(5,3)
E

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [21]:
L = E / A
L

array([[0.        , 0.33333333, 0.4       ],
       [1.5       , 1.33333333, 1.        ],
       [3.        , 2.33333333, 1.6       ],
       [4.5       , 3.33333333, 2.2       ],
       [6.        , 4.33333333, 2.8       ]])