In [2]:
import numpy as np

In [3]:
# tasks 

In [4]:
# task 1 - Extract all odd number from array A
A = np.array([1,2,5,6,4,8,9,11,51])

B = np.array([A%2==1])
B

array([[ True, False,  True, False, False, False,  True,  True,  True]])

In [5]:
B = (A[A%2==1])

In [6]:
B

array([ 1,  5,  9, 11, 51])

In [7]:
# task replace all odd numbers in array with 0
for i in range(0,A.size):
    if A[i] % 2 == 1 :
        A[i] = 0

In [8]:
A

array([0, 2, 0, 6, 4, 8, 0, 0, 0])

In [10]:
#replace all 0 elements in A
C = np.delete(A, np.where(A ==0))

In [11]:
C

array([2, 6, 4, 8])

In [19]:
#create a boolean array that has only True values
boolean = np.full((1,3),True,dtype=bool)
boolean

array([[ True,  True,  True]])